config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :inboxes do
    resources :messages, only: %i[create destroy], module: :inboxes do
      member do
        patch :upvote
        patch :change_status
      end
    end
  end
  root 'static_pages#landing_page'
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_errors.html.erb
<% if form.object.errors.any? %>
  <div style="color: red">
    <h4><%= pluralize(form.object.errors.count, "error") %> prohibited this record from being saved:</h4>

    <ul>
      <% form.object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div data-controller="autohide">
        <%= content_tag :div, value, id: "#{key}" %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<hr>
<center>
  <%= link_to_unless_current 'Pricing', pricing_path %>
  <%= link_to_unless_current 'Privacy', privacy_path %>
  <%= link_to_unless_current 'Terms', terms_path %>
</center>

app/views/shared/_navigation.html.erb
<center>
	<h1>
		<%= link_to_unless_current Rails.application.class.module_parent.name, root_path %>        
	</h1>
	<%= link_to_unless_current 'Inboxes', inboxes_path %>
	<%= link_to_unless_current 'New Inbox', new_inbox_path %>
	<% if signed_in? %>
	  <%= image_tag current_user.image, size: '30x30', alt: "#{current_user.email}" if current_user.image? %>
	  <%= current_user.name %>
	  <%= current_user.uid %>
	  <%= current_user.provider %>

		<%= link_to current_user.email, edit_user_registration_path %>
		<%= button_to "Log out",
									destroy_user_session_path,
									method: :delete,
									data: { turbo: "false" } %>
	<% else %>
		<%= link_to "Log in", new_user_session_path %>
		<%= link_to "Register", new_user_registration_path %>
	<% end %>
</center>

<hr>