config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :inboxes do
    resources :messages, only: %i[create destroy], module: :inboxes do
      member do
        patch :upvote
        patch :change_status
      end
    end
  end
  root 'static_pages#landing_page'
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { order(created_at: :desc) }, dependent: :destroy, inverse_of: :inbox

  MIN_NAME = 6
  MAX_NAME = 100

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: MIN_NAME..MAX_NAME }

  extend FriendlyId
  friendly_id :name, use: %i[slugged finders]
end

app/controllers/inboxes/messages_controller.rb
module Inboxes
  class MessagesController < ApplicationController
    before_action :set_inbox
    before_action :set_message, only: %i[change_status upvote]

    def change_status
      @message.update(status: params[:status])
      flash.now[:notice] = "Status for message #{@message.id} : #{@message.status}"
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            render_turbo_flash,
            turbo_stream.replace(@message,
                                 partial: 'inboxes/messages/message',
                                 locals: { message: @message })
          ]
        end
      end
    end

    def upvote
      @message.upvote! current_user
      flash.now[:notice] = 'Voted!'

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            render_turbo_flash,
            turbo_stream.replace(@message,
                                 partial: 'inboxes/messages/message',
                                 locals: { message: @message })
          ]
        end
      end
    end

    # POST /messages or /messages.json
    def create
      @message = @inbox.messages.new(message_params)

      respond_to do |format|
        if @message.save
          format.turbo_stream do
            flash.now[:notice] = "Message #{@message.id} created!"
            render turbo_stream: [
              render_turbo_flash,
              turbo_stream.update('new_message',
                                  partial: 'inboxes/messages/form',
                                  locals: { message: Message.new }),
              turbo_stream.update('message_counter', @inbox.messages_count),
              turbo_stream.prepend('message_list',
                                   partial: 'inboxes/messages/message',
                                   locals: { message: @message })
            ]
          end
          format.html { redirect_to @inbox, notice: 'Message was successfully created.' }
        else
          format.turbo_stream do
            flash.now[:alert] = 'Something went wrong...'
            render turbo_stream: [
              render_turbo_flash,
              turbo_stream.update('new_message',
                                  partial: 'inboxes/messages/form',
                                  locals: { message: @message })
            ]
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /messages/1 or /messages/1.json
    def destroy
      @message = @inbox.messages.find(params[:id])
      @message.destroy
      respond_to do |format|
        flash.now[:notice] = "Message #{@message.id} destroyed!"
        format.turbo_stream
        format.html { redirect_to @inbox, notice: 'Message was successfully destroyed.' }
      end
    end

    private

    def set_message
      @message = @inbox.messages.find(params[:id])
    end

    def set_inbox
      @inbox = Inbox.find(params[:inbox_id])
    end

    def message_params
      params.require(:message).permit(:body).merge(user: current_user)
    end
  end
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[show edit update destroy]
  before_action :authorize_inbox, only: %i[edit update destroy]

  def index
    set_meta_tags title: %w[Inboxes All]
    # @inboxes = Inbox.all
    @q = Inbox.ransack(params[:q])
    @inboxes = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    set_meta_tags title: ['Inboxes', @inbox.name]
  end

  def new
    set_meta_tags title: 'Add New Inbox'
    @inbox = Inbox.new
  end

  def edit
    set_meta_tags title: "Editing #{@inbox.name}"
  end

  def create
    @inbox = current_user.inboxes.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: 'Inbox was successfully destroyed.' }
    end
  end

  private

  def authorize_inbox
    authorize @inbox
  end

  def set_inbox
    @inbox = Inbox.find(params[:id])
  end

  def inbox_params
    params.require(:inbox).permit(:name, :theme_color)
  end
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
  <%= render 'shared/errors', form: form %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, autocomplete: 'off',
                               style: 'width: 100%; padding: 5px 10px;',
                               maxlength: Inbox::MAX_NAME %>
  </div>

  <div>
    <%= form.label :theme_color, style: "display: block" %>
    <%= form.color_field :theme_color %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>"
     class="scaffold_record"
     style="background-color: <%= inbox.theme_color %>;">

  <h3>
    <%= link_to inbox.name, inbox %>
  </h3>

  <%= link_to "Edit", edit_inbox_path(inbox) if policy(inbox).edit?%>
  <%= button_to "Destroy", inbox, method: :delete if policy(inbox).destroy? %>

  Messages:
  <%= inbox.messages_count %>
  <br>

  <i>
    by
    <%= inbox.user.email %>
    on
    <%= inbox.created_at.strftime('%d/%b/%Y') %>
  </i>
</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Cancel", @inbox %>
</div>

app/views/inboxes/index.html.erb
<h1>
  Inboxes:
  <%= @inboxes.length %>
</h1>

<%= search_form_for @q, html: { autocomplete: 'off' }, data: {turbo_frame: "search"} do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>

<%= turbo_frame_tag 'search' do %>

  <%= sort_link(@q, :name, default_order: :desc) %>
  <%= sort_link(@q, :created_at, default_order: :desc) %>
  <%= sort_link(@q, :messages_count, default_order: :desc) %>
  <%= link_to "Clear search", request.path if request.query_parameters.any? %>


<% end %>

  <div id="inboxes">
    <%= render @inboxes %>
  </div>

app/views/inboxes/new.html.erb
<h1>New Inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Cancel", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<%= render @inbox %>

<h1>
  Messages:
  <span id="message_counter">
    <%= @inbox.messages_count %>
  </span>
</h1>

<div id="new_message">
  <%= render 'inboxes/messages/form', message: Message.new %>
</div>

<div id="message_list">
  <%= render partial: 'inboxes/messages/message', collection: @inbox.messages %>
</div>